server.port=9090

cloud.aws.region.static= ap-south-1
cloud.aws.region.auto = false

cloud.aws.credentials.accessKey = AKIAWN62ESUJYLBSNXGI
cloud.aws.credentials.secretKey = 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
cloud.aws.endpoint.uri = https://sqs.ap-south-1.amazonaws.com/442302240019/MySampleQueue
cloud.aws.stack.auto=false 